// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnIHy-3F8PF8DN2uYZMCBC0745U9AHoGA',
    appId: '1:13656815449:web:58682f6cd6d3ebeebcfe48',
    messagingSenderId: '13656815449',
    projectId: 'flutter-1-31a5a',
    authDomain: 'flutter-1-31a5a.firebaseapp.com',
    storageBucket: 'flutter-1-31a5a.firebasestorage.app',
    measurementId: 'G-WD2DPPN2B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqiy6dNcna3HRc1i-70r1Z86qGi6vNoj0',
    appId: '1:13656815449:android:5a85221f134b7b08bcfe48',
    messagingSenderId: '13656815449',
    projectId: 'flutter-1-31a5a',
    storageBucket: 'flutter-1-31a5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsbWBplUxP0DT56WLoiRgQcbK6U_no1aU',
    appId: '1:13656815449:ios:d4c7c0f30da1bd1dbcfe48',
    messagingSenderId: '13656815449',
    projectId: 'flutter-1-31a5a',
    storageBucket: 'flutter-1-31a5a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsbWBplUxP0DT56WLoiRgQcbK6U_no1aU',
    appId: '1:13656815449:ios:d4c7c0f30da1bd1dbcfe48',
    messagingSenderId: '13656815449',
    projectId: 'flutter-1-31a5a',
    storageBucket: 'flutter-1-31a5a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnIHy-3F8PF8DN2uYZMCBC0745U9AHoGA',
    appId: '1:13656815449:web:b1939b70ece84d9ebcfe48',
    messagingSenderId: '13656815449',
    projectId: 'flutter-1-31a5a',
    authDomain: 'flutter-1-31a5a.firebaseapp.com',
    storageBucket: 'flutter-1-31a5a.firebasestorage.app',
    measurementId: 'G-TK4CXX9QD6',
  );
}
